#!/usr/bin/env node
/**
 * Error registry codegen — runs as a `postbuild` hook.
 *
 * Reads the just-built `dist/index.mjs` (so we don't need TS execution at
 * codegen time), calls `listErrorEntries()`, and emits two artefacts:
 *
 *   1. `dist/errors-manifest.json` — JSON catalogue published with the
 *      package (the `files: ["dist"]` whitelist in package.json carries it
 *      into the tarball).
 *
 *   2. `docs/errors/VTTF-NNNN.md` and `apps/docs/errors/VTTF-NNNN.md` — one
 *      Markdown stub per code, for GitHub and for the docs site.
 *      These are committed so the `docsUrl` resolves to a real page once
 *      the docs site goes live in v0.3.
 *
 * Runs as `postbuild` (not `prebuild`) so the script imports the built
 * ESM directly instead of needing tsx / unrun to load the TS source.
 */

import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { dirname, resolve } from 'node:path';
import { pathToFileURL } from 'node:url';

const PKG_DIR = resolve(import.meta.dirname, '..');
const REPO_ROOT = resolve(PKG_DIR, '..', '..');
const DIST = resolve(PKG_DIR, 'dist');
const MANIFEST_PATH = resolve(DIST, 'errors-manifest.json');
// Two destinations, one source. The repo copy is what a reader browsing
// GitHub lands on; the docs copy is what the site publishes. Generating both
// keeps them from drifting, which a manual copy would not.
const DOCS_DIRS = [
  resolve(REPO_ROOT, 'docs', 'errors'),
  resolve(REPO_ROOT, 'apps', 'docs', 'errors'),
];
const MANIFEST_VERSION = 1;
const SOURCE_RELATIVE = 'packages/core/src/errors/registry.ts';
const SOURCE_URL = `https://github.com/vttforge/vttforge/blob/main/${SOURCE_RELATIVE}`;

async function loadEntries() {
  const distEntry = resolve(DIST, 'index.mjs');
  const distUrl = pathToFileURL(distEntry).href;
  const mod = await import(distUrl);
  if (typeof mod.listErrorEntries !== 'function') {
    throw new Error(
      `dist/index.mjs does not export listErrorEntries — did the build skip the errors registry?`,
    );
  }
  return mod.listErrorEntries();
}

/**
 * The stub deliberately carries no package version.
 *
 * These pages are tracked in git, so stamping the version in would rewrite
 * every one of them on each release — and the release step bumps
 * package.json without running a build, so they would name the previous
 * version until someone rebuilt by hand. It also meant any build on any
 * branch dirtied five tracked files for reasons unrelated to the change.
 *
 * The version still travels with the package in `dist/errors-manifest.json`,
 * which is published and not tracked. A reader who needs it looks there, or
 * at the docs site, which knows the version it was built from.
 */
function renderStub(entry) {
  const lines = [
    `# ${entry.code} — ${entry.name}`,
    '',
    '> [!NOTE]',
    `> ${entry.summary}`,
    '',
    '| Field | Value |',
    '|---|---|',
    `| Code | \`${entry.code}\` |`,
    `| Name | \`${entry.name}\` |`,
    '| Package | `@vttforge/core` |',
    `| Source | [\`${SOURCE_RELATIVE}\`](${SOURCE_URL}) |`,
  ];
  if (entry.deprecated) {
    lines.push('| Status | ⚠️ Deprecated |');
  }
  if (entry.replacedBy) {
    lines.push(`| Replaced by | [\`${entry.replacedBy}\`](./${entry.replacedBy}.md) |`);
  }
  lines.push(
    '',
    '---',
    '',
    'This page is a placeholder. The full diagnostic — root causes, common triggers,',
    'and code samples — lands with the VitePress docs site planned for v0.3.',
    '',
    'Generated by `packages/core/scripts/codegen-errors.mjs` from the registry at',
    `[\`${SOURCE_RELATIVE}\`](${SOURCE_URL}). Do not edit by hand — re-run`,
    '`pnpm --filter @vttforge/core build` after editing the registry.',
    '',
  );
  return lines.join('\n');
}

async function readPkgVersion() {
  const pkg = JSON.parse(await readFile(resolve(PKG_DIR, 'package.json'), 'utf8'));
  return pkg.version;
}

async function writeManifest(entries, pkgVersion) {
  const manifest = {
    version: MANIFEST_VERSION,
    package: '@vttforge/core',
    packageVersion: pkgVersion,
    entries: entries.map((entry) => ({
      code: entry.code,
      name: entry.name,
      summary: entry.summary,
      ...(entry.deprecated ? { deprecated: true } : {}),
      ...(entry.replacedBy ? { replacedBy: entry.replacedBy } : {}),
    })),
  };
  await writeFile(MANIFEST_PATH, `${JSON.stringify(manifest, null, 2)}\n`, 'utf8');
  return manifest;
}

async function writeStubs(entries) {
  for (const dir of DOCS_DIRS) {
    await mkdir(dir, { recursive: true });
    for (const entry of entries) {
      const path = resolve(dir, `${entry.code}.md`);
      await mkdir(dirname(path), { recursive: true });
      await writeFile(path, renderStub(entry), 'utf8');
    }
  }
}

async function main() {
  const [entries, pkgVersion] = await Promise.all([loadEntries(), readPkgVersion()]);
  if (entries.length === 0) {
    throw new Error('Error registry is empty — refusing to overwrite docs/errors with nothing.');
  }
  const manifest = await writeManifest(entries, pkgVersion);
  await writeStubs(entries);
  console.warn(
    `[codegen-errors] wrote ${entries.length} entries → dist/errors-manifest.json + docs/errors/ + apps/docs/errors/`,
  );
  return manifest;
}

main().catch((err) => {
  console.error('[codegen-errors] failed:', err);
  process.exit(1);
});
