import { existsSync, readdirSync, readFileSync } from 'node:fs';
import { defineConfig } from 'vitepress';

/**
 * The error pages are generated. `packages/core/scripts/codegen-errors.mjs`
 * writes one Markdown file per code in the registry, so the sidebar is read
 * from the directory rather than hand-listed — a new error code appears in
 * the docs by existing, not by someone remembering to add it here.
 */
function errorPages() {
  return readdirSync(new URL('../errors', import.meta.url))
    .filter((f) => f.endsWith('.md') && f !== 'index.md')
    .sort()
    .map((f) => ({ text: f.replace('.md', ''), link: `/errors/${f.replace('.md', '')}` }));
}

/**
 * The API reference is generated by `scripts/typedoc.mjs` before the build,
 * one directory per package, each with the sidebar TypeDoc wrote for it.
 */
const REFERENCE_PACKAGES = ['core', 'types', 'cli', 'vite-plugin', 'testing'];

function referenceSidebar() {
  const items = [{ text: 'Overview', link: '/reference/' }];
  for (const name of REFERENCE_PACKAGES) {
    const file = new URL(`../reference/${name}/typedoc-sidebar.json`, import.meta.url);
    if (!existsSync(file)) continue;
    items.push({
      text: `@vttforge/${name}`,
      collapsed: true,
      link: `/reference/${name}/`,
      // TypeDoc writes `.md` links; VitePress serves clean URLs.
      items: JSON.parse(readFileSync(file, 'utf8').replaceAll('.md"', '"')),
    });
  }
  return [{ text: 'API reference', items }];
}

export default defineConfig({
  title: 'VTTForge',
  // The landing page owns the root of vttforge.dev; the docs live under it,
  // in one Pages artifact.
  base: '/docs/',
  description: 'An SDK and CLI for building Foundry VTT v13+ systems and modules.',
  cleanUrls: true,
  lastUpdated: true,

  themeConfig: {
    // Was Pagefind, which built an index nothing ever loaded: no theme
    // component mounted its UI, so the navbar search slot rendered empty and
    // the site shipped with no search at all. At twenty pages VitePress's own
    // local index is enough, and it is one line instead of a component plus
    // asset loading.
    search: { provider: 'local' },

    nav: [
      { text: 'Guide', link: '/guide/getting-started' },
      { text: 'Recipes', link: '/recipes/' },
      { text: 'API', link: '/reference/' },
      { text: 'Errors', link: '/errors/' },
      { text: 'Stability', link: '/stability' },
    ],

    sidebar: {
      '/guide/': [
        {
          text: 'Guide',
          items: [
            { text: 'Getting started', link: '/guide/getting-started' },
            { text: 'Data models', link: '/guide/data-models' },
            { text: 'Sheets', link: '/guide/sheets' },
            { text: 'Modules', link: '/guide/modules' },
            { text: 'Settings and migrations', link: '/guide/settings-and-migrations' },
            { text: 'The dev loop', link: '/guide/dev-loop' },
            { text: 'Testing', link: '/guide/testing' },
            { text: 'CLI reference', link: '/guide/cli' },
          ],
        },
      ],
      '/recipes/': [
        {
          text: 'Recipes',
          items: [
            { text: 'Overview', link: '/recipes/' },
            { text: 'Migrating from v12', link: '/recipes/migrating-from-v12' },
            { text: 'Theme V2 binding', link: '/recipes/theme-v2' },
            { text: 'A theme of your own', link: '/recipes/custom-theme' },
            { text: 'Tailwind', link: '/recipes/tailwind' },
          ],
        },
      ],
      '/reference/': referenceSidebar(),
      '/errors/': [
        { text: 'Error codes', items: [{ text: 'Overview', link: '/errors/' }, ...errorPages()] },
      ],
    },

    socialLinks: [{ icon: 'github', link: 'https://github.com/vttforge/vttforge' }],

    footer: {
      message: 'MIT licensed.',
      copyright: 'Not affiliated with Foundry Gaming LLC.',
    },
  },
});
