import { transformerTwoslash } from '@shikijs/vitepress-twoslash';
import { defineVersionedConfig } from '@viteplus/versions';
import { existsSync, readdirSync, readFileSync } from 'node:fs';

/**
 * The error pages are generated. `packages/core/scripts/codegen-errors.mjs`
 * writes one Markdown file per code in the registry, so the sidebar is read
 * from the directory rather than hand-listed — a new error code appears in
 * the docs by existing, not by someone remembering to add it here.
 */
function errorPages() {
  return readdirSync(new URL('../src/errors', import.meta.url))
    .filter((f) => f.endsWith('.md') && f !== 'index.md')
    .sort()
    .map((f) => ({ text: f.replace('.md', ''), link: `/errors/${f.replace('.md', '')}` }));
}

/**
 * The API reference is generated by `scripts/typedoc.mjs` before the build,
 * one directory per package, each with the sidebar TypeDoc wrote for it.
 */
const REFERENCE_PACKAGES = ['core', 'types', 'cli', 'vite-plugin', 'testing'];

function referenceSidebar() {
  const items = [{ text: 'Overview', link: '/reference/' }];
  for (const name of REFERENCE_PACKAGES) {
    const file = new URL(`../src/reference/${name}/typedoc-sidebar.json`, import.meta.url);
    if (!existsSync(file)) continue;
    items.push({
      text: `@vttforge/${name}`,
      collapsed: true,
      link: `/reference/${name}/`,
      // TypeDoc writes `.md` links; VitePress serves clean URLs.
      items: JSON.parse(readFileSync(file, 'utf8').replaceAll('.md"', '"')),
    });
  }
  return [{ text: 'API reference', items }];
}

export default defineVersionedConfig({
  title: 'VTTForge',
  // The landing page owns the root of vttforge.dev; the docs live under it,
  // in one Pages artifact.
  base: '/docs/',
  description: 'An SDK and CLI for building Foundry VTT v14+ systems and modules.',

  head: [
    // Absolute paths, because head entries are not prefixed with `base`.
    ['link', { rel: 'icon', type: 'image/svg+xml', href: '/docs/favicon.svg' }],
    ['meta', { property: 'og:type', content: 'website' }],
    ['meta', { property: 'og:site_name', content: 'VTTForge' }],
    ['meta', { property: 'og:image', content: 'https://vttforge.dev/social-card.png' }],
    ['meta', { name: 'twitter:card', content: 'summary_large_image' }],
    ['meta', { name: 'twitter:image', content: 'https://vttforge.dev/social-card.png' }],
    ['link', { rel: 'preconnect', href: 'https://fonts.googleapis.com' }],
    ['link', { rel: 'preconnect', href: 'https://fonts.gstatic.com', crossorigin: '' }],
    [
      'link',
      {
        rel: 'stylesheet',
        href: 'https://fonts.googleapis.com/css2?family=Bricolage+Grotesque:opsz,wght@12..96,500;12..96,600;12..96,700&family=Hanken+Grotesk:wght@400;500;600;700&family=JetBrains+Mono:wght@400;500;700&display=swap',
      },
    ],
    // VitePress selects dark with a class on <html>; the Forge tokens read
    // `[data-theme]`. Mirror one onto the other, here in the head so it is
    // set before first paint, and again on every toggle.
    [
      'script',
      {},
      `(() => {
        const el = document.documentElement;
        const sync = () =>
          el.setAttribute('data-theme', el.classList.contains('dark') ? 'dark' : 'light');
        sync();
        new MutationObserver(sync).observe(el, { attributes: true, attributeFilter: ['class'] });
      })();`,
    ],
  ],
  cleanUrls: true,
  lastUpdated: true,
  // The app's own readme sits next to `src/`, not in it, and is not a page.
  srcExclude: ['README.md'],

  /**
   * Twoslash runs the TypeScript compiler over a code block and renders the
   * types it found. It is slow, so a block opts in by tagging itself
   * `ts twoslash`. Everything else is highlighted the way it always was.
   *
   * A twoslash block is typechecked at build time against the packages in
   * `devDependencies`. A snippet that stops compiling after an API change
   * fails the build, which is the point, and the reason to keep the number
   * of them small.
   */
  markdown: {
    codeTransformers: [transformerTwoslash({ explicitTrigger: true })],
  },

  /**
   * Versioned docs.
   *
   * `src/` is the version being written and is served at the root. Each
   * folder under `archive/` is a frozen copy of an older one, served at its
   * own path, with its own sidebar. The switcher in the navigation moves
   * between them.
   *
   * `archive/` is empty today. Cutting a version means copying `src/` into
   * `archive/v<minor>/` and moving `current` on, and the first copy is worth
   * making when the API in `src/` stops describing the published packages.
   * Freezing a copy of what is already at the root only doubles the site and
   * the search index.
   */
  versionsConfig: {
    current: 'v0.17',
    versionSwitcher: { text: 'Version', includeCurrentVersion: true },
  },

  /**
   * One canonical URL per page, derived from the file it was built from.
   *
   * The docs are reachable at more than one path (a directory and its
   * `index.html`), and the generated API reference repeats names across
   * packages. Naming the canonical leaves the crawler nothing to guess.
   */
  transformPageData(pageData) {
    const path = pageData.relativePath.replace(/(index)?\.md$/, '');
    pageData.frontmatter.head ??= [];
    pageData.frontmatter.head.push([
      'link',
      { rel: 'canonical', href: `https://vttforge.dev/docs/${path}` },
    ]);
  },

  themeConfig: {
    logo: '/logo.svg',

    // Was Pagefind, which built an index nothing ever loaded: no theme
    // component mounted its UI, so the navbar search slot rendered empty and
    // the site shipped with no search at all. At twenty pages VitePress's own
    // local index is enough, and it is one line instead of a component plus
    // asset loading.
    search: { provider: 'local' },

    nav: [
      { text: 'Guide', link: '/guide/getting-started' },
      { text: 'Recipes', link: '/recipes/' },
      { text: 'API', link: '/reference/' },
      { text: 'Errors', link: '/errors/' },
      { text: 'Stability', link: '/stability' },
      { text: 'Transparency', link: '/transparency' },
      // Absolute, because a root-relative link would be prefixed with the
      // `/docs/` base and point back into the docs.
      { text: 'Design System', link: 'https://vttforge.dev/design-system' },
      { text: 'vttforge.dev', link: 'https://vttforge.dev/' },
      { component: 'VersionSwitcher' },
    ],

    sidebar: {
      '/guide/': [
        {
          text: 'Guide',
          items: [
            { text: 'Getting started', link: '/guide/getting-started' },
            { text: 'The startup lifecycle', link: '/guide/lifecycle' },
            { text: 'Data models', link: '/guide/data-models' },
            { text: 'Sheets', link: '/guide/sheets' },
            { text: 'Rolls', link: '/guide/rolls' },
            { text: 'Dialogs', link: '/guide/dialogs' },
            { text: 'Modules', link: '/guide/modules' },
            { text: 'Settings and migrations', link: '/guide/settings-and-migrations' },
            { text: 'Keywords', link: '/guide/keywords' },
            { text: 'Decorators', link: '/guide/decorators' },
            { text: 'The dev loop', link: '/guide/dev-loop' },
            { text: 'Testing', link: '/guide/testing' },
            { text: 'CLI reference', link: '/guide/cli' },
          ],
        },
      ],
      '/recipes/': [
        {
          text: 'Recipes',
          items: [
            { text: 'Overview', link: '/recipes/' },
            { text: 'Migrating from v12', link: '/recipes/migrating-from-v12' },
            { text: 'Migrating to v14', link: '/recipes/migrating-to-v14' },
            { text: 'Adopting an existing system', link: '/recipes/adopting-an-existing-system' },
            { text: 'Theme V2 binding', link: '/recipes/theme-v2' },
            { text: 'A theme of your own', link: '/recipes/custom-theme' },
            { text: 'Tailwind', link: '/recipes/tailwind' },
          ],
        },
      ],
      '/reference/': referenceSidebar(),
      '/errors/': [
        { text: 'Error codes', items: [{ text: 'Overview', link: '/errors/' }, ...errorPages()] },
      ],
    },

    socialLinks: [{ icon: 'github', link: 'https://github.com/vttforge/vttforge' }],

    footer: {
      message: 'MIT licensed.',
      copyright: 'Not affiliated with Foundry Gaming LLC or with The Forge hosting service.',
    },
  },
});
